### PR TITLE
feat: add compatibility with laravel-json-api v3

### PR DESCRIPTION
**Pull request by nelson6e65**
Add compatibility with Laravel 10.

## Description

Update valid packages ranges to add compatibility with Laravel v10 and Laravel JSON:API v3.

## Motivation and context

Allow to be installed in Laravel 10 and using Laravel JSON:API 3.

## How has this been tested?

There seems not being any public API changes in required packages, just Laravel 10 compatibility.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](https://github.com/swisnl/openapi-spec-generator/blob/master/CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by nelson6e65** [comment]
PS: @JaZo @bbrala @Rocksheep Can you enable issues (or/and community) to ask for features to be accepted before start working on them? 👀

**Comment by JaZo** [comment]
Good point, I've just enabled issues! I think it was disabled by default because this repo is a fork and we didn't notice.

**Review by JaZo — APPROVED** [review]

**Comment by nelson6e65** [comment]
Any release with this soon? 👀

**Comment by JaZo** [comment]
Sure thing, there you go: [0.5.1](https://github.com/swisnl/openapi-spec-generator/releases/tag/0.5.1)!

**Pull request merged**
