### PR TITLE
Add support for Laravel 11

### PR DESCRIPTION
**Pull request by pjotrvdh**
## Description

This pull request updates the version numbers in the composer.json file to reflect the latest stable releases of the dependencies.

## Motivation and context

I was updating a project to Laravel 11 and was unable to because of missing versions.

## How has this been tested?

I was able to successfully update my project

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](https://github.com/swisnl/openapi-spec-generator/blob/master/CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [x] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by tommie1001** [comment]
@JaZo wellicht kunnen we 7.4 weghalen met een nieuwe versie?

**Comment by JaZo** [comment]
> @JaZo wellicht kunnen we 7.4 weghalen met een nieuwe versie?

The tests for 8.2 and 8.3 were failing, so that wasn't the problem. Although I'm okay with removing support for 7.4 if it's blocking.

**Comment by tommie1001** [comment]
Perhaps not blocking, but I think its better to release new versions for the current supported php versions instead of giving support for unsupported php versions

**Review by JaZo — APPROVED** [review]

**Comment by JaZo** [comment]
As long as it doesn't get in our way I usually leave it so we don't force anyone to update, but if it gets in the way at all I remove it immediately. @Rocksheep is working on a new feature that requires PHP 8 features (https://github.com/swisnl/openapi-spec-generator/pull/18), so he removed 7.4 support there. So eventually support will be dropped.

**Pull request merged**
